# Generated by Django 6.0.2 on 2026-03-03 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_city', models.CharField(max_length=100)),
                ('preferred_city', models.CharField(blank=True, max_length=100, null=True)),
                ('job_sector', models.CharField(blank=True, max_length=100, null=True)),
                ('salary_range', models.CharField(blank=True, max_length=50, null=True)),
                ('commute_time', models.PositiveIntegerField(blank=True, null=True)),
                ('transport_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('housing_priority', models.CharField(blank=True, max_length=20, null=True)),
                ('health_priority', models.CharField(blank=True, max_length=20, null=True)),
                ('education_priority', models.CharField(blank=True, max_length=20, null=True)),
                ('cost_priority', models.CharField(blank=True, max_length=20, null=True)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
