# Generated by Django 6.0.2 on 2026-03-03 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_citizendata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicymakerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_city', models.CharField(max_length=100)),
                ('policy_focus', models.CharField(blank=True, max_length=100, null=True)),
                ('migration_trend', models.CharField(blank=True, max_length=50, null=True)),
                ('infrastructure_pressure', models.CharField(blank=True, max_length=50, null=True)),
                ('housing_status', models.CharField(blank=True, max_length=50, null=True)),
                ('transport_status', models.CharField(blank=True, max_length=50, null=True)),
                ('employment_status', models.CharField(blank=True, max_length=50, null=True)),
                ('environmental_status', models.CharField(blank=True, max_length=50, null=True)),
                ('budget_level', models.CharField(blank=True, max_length=50, null=True)),
                ('policy_notes', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
