# Generated by Django 6.0.2 on 2026-03-03 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_policymakerdata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150)),
                ('business_sector', models.CharField(blank=True, max_length=100, null=True)),
                ('current_city', models.CharField(blank=True, max_length=100, null=True)),
                ('target_city', models.CharField(blank=True, max_length=100, null=True)),
                ('employee_count', models.PositiveIntegerField(blank=True, null=True)),
                ('office_cost_level', models.CharField(blank=True, max_length=50, null=True)),
                ('talent_availability', models.CharField(blank=True, max_length=50, null=True)),
                ('infrastructure_quality', models.CharField(blank=True, max_length=50, null=True)),
                ('business_growth_status', models.CharField(blank=True, max_length=50, null=True)),
                ('relocation_interest', models.CharField(blank=True, max_length=50, null=True)),
                ('corporate_notes', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
