# Generated by Django 6.0.3 on 2026-03-28 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_corporatedata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100, unique=True)),
                ('division', models.CharField(blank=True, max_length=100, null=True)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('cost_of_living_index', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('infrastructure_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommuteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_commute_distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('daily_commute_time_minutes', models.IntegerField(blank=True, null=True)),
                ('transport_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.city')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_name', models.CharField(max_length=100)),
                ('job_count', models.IntegerField(blank=True, null=True)),
                ('avg_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_sectors', to='authentication.city')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('employee_count', models.IntegerField(blank=True, null=True)),
                ('relocation_possible', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.city')),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.jobsector')),
            ],
        ),
        migrations.CreateModel(
            name='PolicySimReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_name', models.CharField(blank=True, max_length=100, null=True)),
                ('relocated_jobs', models.IntegerField(blank=True, null=True)),
                ('estimated_traffic_reduction_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('estimated_pollution_reduction_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('report_date', models.DateField(blank=True, null=True)),
                ('source_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_reports_source', to='authentication.city')),
                ('target_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_reports_target', to='authentication.city')),
            ],
        ),
        migrations.CreateModel(
            name='PollutionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pm25', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('air_quality_level', models.CharField(blank=True, max_length=50, null=True)),
                ('estimated_vehicle_emission', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pollution_records', to='authentication.city')),
            ],
        ),
        migrations.CreateModel(
            name='QoLIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('healthcare_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('education_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('safety_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('housing_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('final_qol_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qol_records', to='authentication.city')),
            ],
        ),
        migrations.CreateModel(
            name='TrafficData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_commute_time_minutes', models.IntegerField(blank=True, null=True)),
                ('congestion_level', models.CharField(blank=True, max_length=50, null=True)),
                ('daily_delay_minutes', models.IntegerField(blank=True, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffic_records', to='authentication.city')),
            ],
        ),
    ]
