# Generated by Django 6.0.3 on 2026-03-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_city_commuteprofile_jobsector_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirQualityReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('pm25', models.FloatField(blank=True, null=True)),
                ('aqi', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(default='unknown', max_length=100)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('raw_json', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CityMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100, unique=True)),
                ('pm25_latest', models.FloatField(blank=True, null=True)),
                ('aqi_latest', models.FloatField(blank=True, null=True)),
                ('traffic_minutes_latest', models.FloatField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('aqi_source', models.CharField(default='unknown', max_length=100)),
                ('traffic_source', models.CharField(default='unknown', max_length=100)),
            ],
        ),
    ]
