# Generated by Django 6.0.3 on 2026-04-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_airqualityreading_citymetric'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalAQI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('aqi', models.FloatField(blank=True, null=True)),
                ('pm25', models.FloatField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField()),
                ('source', models.CharField(default='Mendeley Bangladesh AQI 2000–2025', max_length=150)),
            ],
            options={
                'indexes': [models.Index(fields=['city_name', 'recorded_at'], name='authenticat_city_na_fee863_idx')],
            },
        ),
    ]
