# Generated by Django 6.0.3 on 2026-04-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_historicalaqi'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='historicalaqi',
            constraint=models.UniqueConstraint(fields=('city_name', 'recorded_at'), name='uniq_city_time'),
        ),
    ]
