# Generated by Django 6.0.3 on 2026-04-16 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_historicalaqi_uniq_city_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollutiondata',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pollutiondata',
            name='raw_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pollutiondata',
            name='source',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='trafficdata',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='trafficdata',
            name='raw_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trafficdata',
            name='source',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
