# Generated by Django 6.0.3 on 2026-04-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_pollutiondata_last_updated_pollutiondata_raw_json_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalCitizenSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_city', models.CharField(blank=True, max_length=100, null=True)),
                ('preferred_city', models.CharField(blank=True, max_length=100, null=True)),
                ('main_problem', models.TextField(blank=True, null=True)),
                ('relocation_reason', models.TextField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
